apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../bases
patchesJson6902:
- target:
    version: apps/v1
    kind: Deployment
    name: metrics-server
    namespace: kube-system
  path: metrics-server-patch.yaml